package catss.kino.entity;

import com.fasterxml.jackson.annotation.JsonBackReference;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

@Getter
@Setter
@Entity
@NoArgsConstructor
public class Reservation {
    // Autogenerated ID
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    int id;

    // The relation between the Reservation and member classes
    @ManyToOne
            @JsonBackReference
    Member member;

    // The relation between the Reservation and Movie classes
    @ManyToOne
            @JsonBackReference
    Showing showing;

    @CreationTimestamp
    protected LocalDateTime created;
    @UpdateTimestamp
    protected LocalDateTime edited;

    @ElementCollection
    List<String> seats;


// A constructor created to make new reservations
    public Reservation(Member member,Showing showing, List<String> seats){
        this.seats = seats;
        this.member = member;
        this.showing = showing;
        member.addReservation(this);
        showing.addReservation(this);
    }
}
