package catss.kino.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDate;
import java.time.LocalDateTime;

@Getter
@Setter
@Entity
@NoArgsConstructor
public class Reservation {
    // Autogenerated ID
    @Id
        @GeneratedValue(strategy = GenerationType.IDENTITY)
    int id;

    LocalDate bookingDate;


    // The relation between the Reservation and member classes
    @ManyToOne
    Member member;

    // The relation between the Reservation and Movie classes
    @ManyToOne
    Movie movie;

    @CreationTimestamp
    protected LocalDateTime created;
    @UpdateTimestamp
    protected LocalDateTime edited;
// A constructor created to make new reservations
    public Reservation(LocalDate bookingDate,Member member,Movie movie){
        this.bookingDate = bookingDate;
        this.member = member;
        member.addReservation(this);
        movie.addReservation(this);

    }

}
