package catss.kino.entity;

import com.fasterxml.jackson.annotation.JsonBackReference;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.cglib.core.Local;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

@Getter
@Setter
@Entity
@NoArgsConstructor
public class Showing {
    // Autogenerated ID
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    int id;

    @ManyToOne
    @JsonBackReference
    Movie movie;

    int hallId;


    LocalDateTime start;
    LocalDateTime end;
    double price;
    @OneToMany(mappedBy = "showing")
    List<Reservation> reservations;

    // Adds the reservation to a list with the movies, that can get accessed by any class.
    public void addReservation(Reservation reservation){
        if (reservations == null){
            reservations = new ArrayList<>();
        }
        reservations.add(reservation);
    }

    public Showing(Movie movie, int hallId, LocalDateTime start, Long lengthInMinutes, double price) {
        this.movie = movie;
        this.hallId = hallId;
        this.start = start;
        this.end = start.plusMinutes(lengthInMinutes);
        this.price = price;
        this.reservations = new ArrayList<>();
        movie.addShowing(this);
    }

    public List<Integer> getReservationIds() {
        return reservations.stream().map(reservation -> reservation.id).collect(Collectors.toList());
    }
}
